---
- hosts: all
  tasks:
    - file: path=/etc/zprofile state=absent
      become: yes
      become_method: sudo

    - file: path=~/.zsh state=directory
    - file: path=~/.zsh/custom state=directory
    - file: src={{ curdir }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - ansible.cfg
        - irbrc
        - gemrc
        - gitconfig
        - gitignore
        - pryrc
        - spring.rb
        - zshenv
        - zshrc
        - zsh/custom/bundler.plugin.zsh
        - zsh/custom/git.plugin.zsh
        - zsh/custom/spring.plugin.zsh
        - zsh/custom/unix.plugin.zsh
        - zsh/custom/vim.plugin.zsh
        - zsh/custom/rspec.plugin.zsh
        - zsh/custom/sshrc.plugin.zsh
        - sshrc

    - file: src={{ curdir }}/zsh/themes/exaspark.zsh-theme dest=~/.oh-my-zsh/themes/exaspark.zsh-theme state=link

    - cron:
        name: "Backup configs"
        minute: "0" # every hour
        job: "cd {{ curdir }} && ansible-playbook ansible/backup_configs.yml -i ansible/local"

    - lineinfile:
        dest: "/etc/syslog.conf"
        regexp: 'cron\.\* '
        line: "cron.*      /var/log/syslog.cron.log"
      become: yes
      become_method: sudo
    - shell: >
        launchctl unload /System/Library/LaunchDaemons/com.apple.syslogd.plist &&
        launchctl load /System/Library/LaunchDaemons/com.apple.syslogd.plist
      become: yes
      become_method: sudo

    - git: repo=git@github.com:zsh-users/zsh-autosuggestions.git dest=~/.zsh/zsh-autosuggestions clone=yes update=no

    - file: path=~/.sshrc.d state=directory
    - file: src={{ curdir }}/zsh/custom/{{ item }} dest=~/.sshrc.d/{{ item }} state=link
      with_items:
        - bundler.plugin.zsh
        - git.plugin.zsh
        - spring.plugin.zsh
        - unix.plugin.zsh
        - vim.plugin.zsh
    - file: src={{ curdir }}/{{ item }} dest=~/.sshrc.d/{{ item }} state=link
      with_items:
        - vimrc
        - irbrc
