---
- hosts: all
  tasks:
    - file: src={{ curdir }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc
        - vimrc.bundles
    - file: path=~/.vim/autoload state=directory
    - get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.vim/autoload/plug.vim
    - command: vim +PlugInstall +qall
    - command: ~/.vim/plugged/YouCompleteMe/install.py --clang-completer
    - command: npm -g install instant-markdown-d
    - command: gem install gem-ctags
    - command: gem ctags
