---
- hosts: all
  tasks:
    - file: src={{ curdir }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc
        - vimrc.bundles

    - file: path=~/.vim/autoload state=directory
    - get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.vim/autoload/plug.vim
    - shell: vim +PlugInstall! +qall

    - stat: path=~/.vim/plugged/YouCompleteMe/third_party/ycmd/ycm_core.so
      register: ycm_core
    - shell: ./install.py --clang-completer --gocode-completer --tern-completer
      args:
        chdir: ~/.vim/plugged/YouCompleteMe
      when: ycm_core.stat.exists == False

    - shell: npm -g install instant-markdown-d
    - shell: gem install gem-ctags
