---
- hosts: all
  tasks:
    - file: path=/etc/zprofile state=absent
      become: yes
      become_user: root
    - file: path=/etc/zprofile state=touch owner=root group=wheel mode=0444
      become: yes
      become_user: root

    - file: path=~/.zsh/custom state=directory
    - file: src={{ curdir }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - irbrc
        - gemrc
        - gitconfig
        - gitignore
        - pryrc
        - spring.rb
        - zshenv
        - zshrc
        - zsh/custom/bundler.plugin.zsh
        - zsh/custom/git.plugin.zsh
        - zsh/custom/spring.plugin.zsh
        - zsh/custom/unix.plugin.zsh
        - zsh/custom/vim.plugin.zsh
        - zsh/custom/rspec.plugin.zsh
        - zsh/custom/sshrc.plugin.zsh
        - sshrc

    - file: path=~/.sshrc.d state=directory
    - file: src={{ curdir }}/zsh/custom/{{ item }} dest=~/.sshrc.d/{{ item }} state=link
      with_items:
        - bundler.plugin.zsh
        - git.plugin.zsh
        - spring.plugin.zsh
        - unix.plugin.zsh
        - vim.plugin.zsh
    - file: src={{ curdir }}/{{ item }} dest=~/.sshrc.d/{{ item }} state=link
      with_items:
        - vimrc
        - irbrc
