---
- hosts: all
  tasks:
    - file: src={{ curdir }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - ackrc
        - irbrc
        - gemrc
        - gitconfig
        - gitignore
        - pryrc
        - spring.rb
        - zshrc
        - oh-my-zsh/custom/bundler.plugin.zsh
        - oh-my-zsh/custom/git.plugin.zsh
        - oh-my-zsh/custom/spring.plugin.zsh
        - oh-my-zsh/custom/unix.plugin.zsh
        - oh-my-zsh/custom/vim.plugin.zsh
        - sshrc
    - file: src={{ curdir }}/zshrc dest=~/.zshenv state=link

    - file: path=~/.sshrc.d state=directory
    - file: src={{ curdir }}/oh-my-zsh/custom/{{ item }} dest=~/.sshrc.d/{{ item }} state=link
      with_items:
        - bundler.plugin.zsh
        - git.plugin.zsh
        - spring.plugin.zsh
        - unix.plugin.zsh
        - vim.plugin.zsh
    - file: src={{ curdir }}/{{ item }} dest=~/.sshrc.d/{{ item }} state=link
      with_items:
        - vimrc
        - irbrc
