---
- hosts: all
  tasks:
    - shell: pip3 install --upgrade neovim

    - file: src={{ curdir }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc
        - vimrc.plugins

    - file: src=~/.vim dest=~/.config/nvim state=link
    - file: src=~/.vimrc dest=~/.config/nvim/init.vim state=link

    - file: path=~/.vim/autoload state=directory
    - get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.vim/autoload/plug.vim
    - shell: nvim +PlugInstall! +qall
      ignore_errors: yes # because of the error: Output is not to a terminal

    - shell: npm -g install instant-markdown-d
    - shell: gem install gem-ctags
