---
- hosts: all
  tasks:
    - file: src={{ curdir }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - ackrc
        - gemrc
        - gitconfig
        - gitignore
        - pryrc
        - spring.rb
        - zshrc
        - oh-my-zsh/custom/bundler.plugin.zsh
        - oh-my-zsh/custom/git.plugin.zsh
        - oh-my-zsh/custom/spring.plugin.zsh
        - oh-my-zsh/custom/unix.plugin.zsh
        - oh-my-zsh/custom/vim.plugin.zsh
