---
- hosts: all
  tasks:
    - shell: echo $ZSH_VERSION
      ignore_errors: yes

    - get_url: url=https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh dest=/tmp/oh_my_zsh_install.sh mode=0744
      when: zsh_version is undefined

    - shell: sh -c /tmp/oh_my_zsh_install.sh
      when: zsh_version is undefined

    - shell: rm /tmp/oh_my_zsh_install.sh
      when: zsh_version is undefined
