---
- hosts: all
  tasks:
    - name: Install Ansible
      shell: pip install ansible
      become: true # should be installed via sudo
      environment:
        PYENV_VERSION: "{{ python_version }}"

    - name: Rehash
      shell: pyenv rehash
