---
- hosts: all
  tasks:
    - shell: |
        if ! [[ "$(eval "brew cask list | grep '^{{ item }}$'")" ]] ; then
          brew install {{ item }}
        fi
      with_items:
        - google-chrome
        - skype
        - dropbox
        - sourcetree
        - evernote
        - tunnelblick
        - sequel-pro
        - mongohub
        - psequel
        - jumpcut
        - flux
        - the-unarchiver
        - mplayerx
        - utorrent
        - libreoffice
        - cyberduck
        - slack
        - android-file-transfer
        - rescuetime
        - pixlr
        - karabiner
        - paragon-ntfs
        - iterm2
    - shell: "{{ curdir }}/iterm2/install-settings.sh" # run in Terminal
