---
- hosts: all
  tasks:
    - shell: brew -v
      register: brew_exists
      ignore_errors: yes

    - get_url: url=https://raw.githubusercontent.com/Homebrew/install/master/install dest=/tmp/homebrew_install.rb
      when: brew_exists|failed

    - shell: ruby /tmp/homebrew_install.rb
      when: brew_exists|failed

    - file: path=/tmp/homebrew_install.rb state=absent
      when: brew_exists|failed
