---
- hosts: all
  tasks:
    - shell: brew update
    - shell: brew tap homebrew/services # e.g. allow 'brew services start mysql' command

    # apps
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
        fi
      with_items:
        - git
        - openssl
        - rbenv
        - ruby-build
        - cmake
        - ctags
        - go
        - imagemagick
        - leiningen
        - sphinx
        - the_silver_searcher
        - vim
        - wget
        - sshrc
        - fzf
        - node
        - unar
        - python3
        - findutils # to use gfind with -print option
        - logstash

    # java for Elasticsearch
    - shell: |
        if ! [[ "$(eval "brew cask list | grep '^java$'")" ]] ; then
          brew install java
        fi

    # services
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
          ln -sfv /usr/local/opt/{{ item }}/*.plist ~/Library/LaunchAgents
        fi
      with_items:
        - elasticsearch
        - kibana
        - memcached
        - mongodb
        - mysql
        - postgresql
        - redis
        - rabbitmq
        - selenium-server-standalone

    # to avoid using flag --with-openssl-dir=/usr/local/opt/openssl
    - shell: brew link --force openssl

    # ruby
    - file: path=~/.rbenv state=absent
    - file: src=/usr/local/opt/rbenv dest=~/.rbenv state=link

    # - shell: brew install phantomjs # v2 currently does not work with OS X El Capitan, use lines below:
    - shell: npm install phantom phantomjs -g

    # elasticsearch plugins
    - shell: /usr/local/Cellar/elasticsearch/*/libexec/bin/plugin install license
    - shell: /usr/local/Cellar/elasticsearch/*/libexec/bin/plugin install marvel-agent
    - shell: kibana plugin --install elastic/sense
    - shell: kibana plugin --install elasticsearch/marvel/latest
    - shell: brew services restart elasticsearch
    - shell: brew services restart kibana

    - shell: pip3 install howdoi
